version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: coachlink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  web:
    build: .
    volumes: [".:/app"]
    ports: ["8000:8000"]
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/coachlink
    depends_on: [db, redis]
    