name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff (lint + format check)
        run: |
          ruff check .
          ruff format --check .

      - name: Django checks
        env:
          DJANGO_DEBUG: "False"
        run: |
          python manage.py check
          # verify migrations are up to date
          python manage.py makemigrations --check --dry-run

      - name: Tests
        run: |
          # prefer pytest; falls back to Django test if needed
          pytest -q || python manage.py test -v
